### ISSUE TITLE
Adjust instructions (or code) for Windows

### ISSUE THREAD

**Issue by christophe-gouel** [yangsheng6810/org-latex-instant-preview#19]
The file `tex2svg` installed with mathjax-node-cli is a script NodeJS that can be launched directly on Linux and macOS thanks to shebang, but Windows doesn't understand shebang. So it took me some time to figure out why things were not working and to make it work.

I see two options:

- Adjust the instructions. Windows users should create a batch file, for example `tex2svg.cmd` containing
```bash
node tex2svg %1
```
and call this file in the configuration
```emacs-lisp
(setq org-latex-impatient-tex2svg-bin
        ;; location of tex2svg executable
        "~/node_modules/mathjax-node-cli/bin/tex2svg.cmd")
```
- Adjust the code to avoid relying on shebang. That would be my preference as it would avoid manual adjustments each time the package is installed.

**Comment by christophe-gouel** [comment]
Sorry, I thought I was making it work but I was getting the preview from org-preview. Still not working on Windows for me.

**Comment by yangsheng6810** [comment]
Thanks for your effort! Please do report back if you find a way to make it work on Windows, and I will be more than happy to adjust code/instruction to share your contributions
