### ISSUE TITLE
Preview auto-hiding not working

### ISSUE THREAD

**Issue by yangsheng6810** [yangsheng6810/org-latex-instant-preview#2]
When cursor moves out of LaTeX fragments or buffer changes, the preview does not auto hide.

**Comment by yangsheng6810** [comment]
@tshu-w Could you check if 1c8f10ae04a951581c88452d1d5cdfd2bf6fad0f fixes it?

**Comment by tshu-w** [comment]
@yangsheng6810 yes, it does fix it.
