### ISSUE TITLE
Support dark themes

### ISSUE THREAD

**Issue by MatthewZMD** [yangsheng6810/org-latex-instant-preview#3]
The default generated text is black, and due to transparent background, it is barely visible in emacs dark theme.

**Comment by MatthewZMD** [comment]
我看了一下`tex2svg`貌似不支持通过parameter更改颜色，直接更改svg反而更方便点，一个比较简单粗暴的解决方案是
```
           :sentinel
           (lambda (&rest _)
             (let ((inhibit-message t))
               (with-current-buffer -posframe-buffer
                 (image-mode-as-text)
                 (erase-buffer)
                 (insert-buffer-substring -output-buffer)
+                (goto-char (point-min))
+                (while (search-forward "currentColor" nil t)
+                  (replace-match "white"))
```

**Comment by yangsheng6810** [comment]
I can think of the following solutions:

1. Modifying SVG file after it is created. This is an ad-hoc solution, and I am not familiar with SVG format. Plus, it puts burden on Emacs and I am reluctant to try it first.
2. Wrap `tex-string` with a `\color{}`. This is the easiest and fastest implementation. While still a bit ad-hoc, I will implement it this way in the short term.
3. Edit or re-write `tex2svg`. The functionality of `tex2svg` is very limited comparing to `mathjax-node` it depends on. In fact, `mathjax-node` provides the option of adding a CSS style when exporting. I think this would be the final way to go.

**Comment by yangsheng6810** [comment]
Could you test if e8d23637e79068e6103ad337a7dac2b1690fb7e7 fixes the issue for you?
